/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebViewerIndexRouteImport } from './routes/_authenticated/web-viewer/index'
import { Route as AuthenticatedStatusPageIndexRouteImport } from './routes/_authenticated/status-page/index'
import { Route as AuthenticatedSshIndexRouteImport } from './routes/_authenticated/ssh/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNetworkIndexRouteImport } from './routes/_authenticated/network/index'
import { Route as AuthenticatedMonitorsIndexRouteImport } from './routes/_authenticated/monitors/index'
import { Route as AuthenticatedLogViewerIndexRouteImport } from './routes/_authenticated/log-viewer/index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'
import { Route as AuthenticatedFilesIndexRouteImport } from './routes/_authenticated/files/index'
import { Route as AuthenticatedDockerIndexRouteImport } from './routes/_authenticated/docker/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedCloudIndexRouteImport } from './routes/_authenticated/cloud/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMonitorsMonitorIdRouteImport } from './routes/_authenticated/monitors/$monitorId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebViewerIndexRoute =
  AuthenticatedWebViewerIndexRouteImport.update({
    id: '/web-viewer/',
    path: '/web-viewer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStatusPageIndexRoute =
  AuthenticatedStatusPageIndexRouteImport.update({
    id: '/status-page/',
    path: '/status-page/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSshIndexRoute = AuthenticatedSshIndexRouteImport.update({
  id: '/ssh/',
  path: '/ssh/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNetworkIndexRoute =
  AuthenticatedNetworkIndexRouteImport.update({
    id: '/network/',
    path: '/network/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitorsIndexRoute =
  AuthenticatedMonitorsIndexRouteImport.update({
    id: '/monitors/',
    path: '/monitors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogViewerIndexRoute =
  AuthenticatedLogViewerIndexRouteImport.update({
    id: '/log-viewer/',
    path: '/log-viewer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFilesIndexRoute = AuthenticatedFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDockerIndexRoute =
  AuthenticatedDockerIndexRouteImport.update({
    id: '/docker/',
    path: '/docker/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCloudIndexRoute = AuthenticatedCloudIndexRouteImport.update({
  id: '/cloud/',
  path: '/cloud/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMonitorsMonitorIdRoute =
  AuthenticatedMonitorsMonitorIdRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/monitors/$monitorId': typeof AuthenticatedMonitorsMonitorIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/cloud/': typeof AuthenticatedCloudIndexRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/docker/': typeof AuthenticatedDockerIndexRoute
  '/files/': typeof AuthenticatedFilesIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/log-viewer/': typeof AuthenticatedLogViewerIndexRoute
  '/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/network/': typeof AuthenticatedNetworkIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/ssh/': typeof AuthenticatedSshIndexRoute
  '/status-page/': typeof AuthenticatedStatusPageIndexRoute
  '/web-viewer/': typeof AuthenticatedWebViewerIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/monitors/$monitorId': typeof AuthenticatedMonitorsMonitorIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/cloud': typeof AuthenticatedCloudIndexRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/docker': typeof AuthenticatedDockerIndexRoute
  '/files': typeof AuthenticatedFilesIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/log-viewer': typeof AuthenticatedLogViewerIndexRoute
  '/monitors': typeof AuthenticatedMonitorsIndexRoute
  '/network': typeof AuthenticatedNetworkIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/ssh': typeof AuthenticatedSshIndexRoute
  '/status-page': typeof AuthenticatedStatusPageIndexRoute
  '/web-viewer': typeof AuthenticatedWebViewerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/monitors/$monitorId': typeof AuthenticatedMonitorsMonitorIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/cloud/': typeof AuthenticatedCloudIndexRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/docker/': typeof AuthenticatedDockerIndexRoute
  '/_authenticated/files/': typeof AuthenticatedFilesIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/log-viewer/': typeof AuthenticatedLogViewerIndexRoute
  '/_authenticated/monitors/': typeof AuthenticatedMonitorsIndexRoute
  '/_authenticated/network/': typeof AuthenticatedNetworkIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/ssh/': typeof AuthenticatedSshIndexRoute
  '/_authenticated/status-page/': typeof AuthenticatedStatusPageIndexRoute
  '/_authenticated/web-viewer/': typeof AuthenticatedWebViewerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/monitors/$monitorId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/agents/'
    | '/alerts/'
    | '/cloud/'
    | '/connections/'
    | '/docker/'
    | '/files/'
    | '/incidents/'
    | '/log-viewer/'
    | '/monitors/'
    | '/network/'
    | '/settings/'
    | '/ssh/'
    | '/status-page/'
    | '/web-viewer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/monitors/$monitorId'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/agents'
    | '/alerts'
    | '/cloud'
    | '/connections'
    | '/docker'
    | '/files'
    | '/incidents'
    | '/log-viewer'
    | '/monitors'
    | '/network'
    | '/settings'
    | '/ssh'
    | '/status-page'
    | '/web-viewer'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/monitors/$monitorId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/agents/'
    | '/_authenticated/alerts/'
    | '/_authenticated/cloud/'
    | '/_authenticated/connections/'
    | '/_authenticated/docker/'
    | '/_authenticated/files/'
    | '/_authenticated/incidents/'
    | '/_authenticated/log-viewer/'
    | '/_authenticated/monitors/'
    | '/_authenticated/network/'
    | '/_authenticated/settings/'
    | '/_authenticated/ssh/'
    | '/_authenticated/status-page/'
    | '/_authenticated/web-viewer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/web-viewer/': {
      id: '/_authenticated/web-viewer/'
      path: '/web-viewer'
      fullPath: '/web-viewer/'
      preLoaderRoute: typeof AuthenticatedWebViewerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/status-page/': {
      id: '/_authenticated/status-page/'
      path: '/status-page'
      fullPath: '/status-page/'
      preLoaderRoute: typeof AuthenticatedStatusPageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ssh/': {
      id: '/_authenticated/ssh/'
      path: '/ssh'
      fullPath: '/ssh/'
      preLoaderRoute: typeof AuthenticatedSshIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/network/': {
      id: '/_authenticated/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof AuthenticatedNetworkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitors/': {
      id: '/_authenticated/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AuthenticatedMonitorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/log-viewer/': {
      id: '/_authenticated/log-viewer/'
      path: '/log-viewer'
      fullPath: '/log-viewer/'
      preLoaderRoute: typeof AuthenticatedLogViewerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/files/': {
      id: '/_authenticated/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof AuthenticatedFilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docker/': {
      id: '/_authenticated/docker/'
      path: '/docker'
      fullPath: '/docker/'
      preLoaderRoute: typeof AuthenticatedDockerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cloud/': {
      id: '/_authenticated/cloud/'
      path: '/cloud'
      fullPath: '/cloud/'
      preLoaderRoute: typeof AuthenticatedCloudIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/monitors/$monitorId': {
      id: '/_authenticated/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AuthenticatedMonitorsMonitorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMonitorsMonitorIdRoute: typeof AuthenticatedMonitorsMonitorIdRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedCloudIndexRoute: typeof AuthenticatedCloudIndexRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
  AuthenticatedDockerIndexRoute: typeof AuthenticatedDockerIndexRoute
  AuthenticatedFilesIndexRoute: typeof AuthenticatedFilesIndexRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
  AuthenticatedLogViewerIndexRoute: typeof AuthenticatedLogViewerIndexRoute
  AuthenticatedMonitorsIndexRoute: typeof AuthenticatedMonitorsIndexRoute
  AuthenticatedNetworkIndexRoute: typeof AuthenticatedNetworkIndexRoute
  AuthenticatedSshIndexRoute: typeof AuthenticatedSshIndexRoute
  AuthenticatedStatusPageIndexRoute: typeof AuthenticatedStatusPageIndexRoute
  AuthenticatedWebViewerIndexRoute: typeof AuthenticatedWebViewerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMonitorsMonitorIdRoute: AuthenticatedMonitorsMonitorIdRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedCloudIndexRoute: AuthenticatedCloudIndexRoute,
  AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  AuthenticatedDockerIndexRoute: AuthenticatedDockerIndexRoute,
  AuthenticatedFilesIndexRoute: AuthenticatedFilesIndexRoute,
  AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  AuthenticatedLogViewerIndexRoute: AuthenticatedLogViewerIndexRoute,
  AuthenticatedMonitorsIndexRoute: AuthenticatedMonitorsIndexRoute,
  AuthenticatedNetworkIndexRoute: AuthenticatedNetworkIndexRoute,
  AuthenticatedSshIndexRoute: AuthenticatedSshIndexRoute,
  AuthenticatedStatusPageIndexRoute: AuthenticatedStatusPageIndexRoute,
  AuthenticatedWebViewerIndexRoute: AuthenticatedWebViewerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
